import type {
  BusinessLikertQuestion,
  BusinessQuestion,
  MbtiLikertQuestion,
  MbtiQuestion,
} from "@/lib/diagnosis/types";

export const mbtiQuestions: MbtiQuestion[] = [
  { id: "mbti-1", text: "あなたは、定期的に新しい友人や知人を作ることが多いですか？", axis: "EI", weight: 2, reverse: false },
  { id: "mbti-2", text: "シンプルで分かりやすい発想よりも、複雑でも新しい発想のほうにワクワクしますか？", axis: "SN", weight: 2, reverse: true },
  { id: "mbti-3", text: "事実に基づいた議論よりも、感情に響く内容のほうが説得力を感じやすいですか？", axis: "TF", weight: 2, reverse: true },
  { id: "mbti-4", text: "生活や仕事の空間は、比較的きれいで整理されていることが多いですか？", axis: "JP", weight: 2, reverse: false },
  { id: "mbti-5", text: "大きなプレッシャーがかかっても、比較的冷静でいられることが多いですか？", axis: "TF", weight: 1, reverse: false },
  { id: "mbti-6", text: "人脈を広げたり、知らない人に自分から話しかけたりするのは、とても大変だと感じますか？", axis: "EI", weight: 2, reverse: true },

  { id: "mbti-7", text: "仕事では優先順位をつけて計画し、締切よりかなり前に終わらせることが多いですか？", axis: "JP", weight: 2, reverse: false },
  { id: "mbti-8", text: "数字やデータよりも、人の物語や感情のほうが強く心に残りますか？", axis: "TF", weight: 1, reverse: true },
  { id: "mbti-9", text: "予定表やリストなど、整理や管理のためのツールを使うのが好きですか？", axis: "JP", weight: 2, reverse: false },
  { id: "mbti-10", text: "些細なミスでも、自分の能力や知識全体を疑ってしまうことがありますか？", axis: "TF", weight: 1, reverse: true },
  { id: "mbti-11", text: "特に準備がなくても、興味のある相手のところへ行って話しかけるのは簡単ですか？", axis: "EI", weight: 2, reverse: false },
  { id: "mbti-12", text: "クリエイティブな作品をどう解釈するかといった議論には、あまり興味がありませんか？", axis: "SN", weight: 1, reverse: false },

  { id: "mbti-13", text: "行動方針を決めるとき、他の人の感情よりも事実を重視することが多いですか？", axis: "TF", weight: 2, reverse: false },
  { id: "mbti-14", text: "何も計画を立てずに、その日を過ごすことがよくありますか？", axis: "JP", weight: 1, reverse: true },
  { id: "mbti-15", text: "会う相手に好印象を残せるかどうかは、あまり気にしないほうですか？", axis: "TF", weight: 1, reverse: false },
  { id: "mbti-16", text: "チームで何かを進めることが好きですか？", axis: "EI", weight: 2, reverse: false },
  { id: "mbti-17", text: "今までやったことのない新しいやり方を試すのは楽しいと感じますか？", axis: "SN", weight: 2, reverse: true },
  { id: "mbti-18", text: "完全に正直であることよりも、相手への思いやりを優先することが多いですか？", axis: "TF", weight: 2, reverse: true },

  { id: "mbti-19", text: "新しい経験や知識を、積極的に追いかけるほうですか？", axis: "SN", weight: 2, reverse: true },
  { id: "mbti-20", text: "物事が悪い方向に進むのではないかと、つい心配しがちですか？", axis: "TF", weight: 1, reverse: true },
  { id: "mbti-21", text: "グループで行う趣味や活動よりも、一人で行うもののほうが楽しいですか？", axis: "EI", weight: 2, reverse: true },
  { id: "mbti-22", text: "仕事として架空の物語を書く自分は、あまり想像できませんか？", axis: "SN", weight: 1, reverse: false },
  { id: "mbti-23", text: "多少感情面を無視してでも、効率的な決断を好みますか？", axis: "TF", weight: 2, reverse: false },
  { id: "mbti-24", text: "やるべきことを終えてから、安心してリラックスしたいタイプですか？", axis: "JP", weight: 2, reverse: false },

  { id: "mbti-25", text: "意見が食い違ったときは、相手の気持ちに配慮するよりも、自分の主張を証明することを優先しがちですか？", axis: "TF", weight: 1, reverse: false },
  { id: "mbti-26", text: "社交の場では、自分からではなく、まず相手が自己紹介するのを待つことが多いですか？", axis: "EI", weight: 1, reverse: true },
  { id: "mbti-27", text: "急に機嫌が変わることがあるほうですか？", axis: "TF", weight: 1, reverse: true },
  { id: "mbti-28", text: "感情的な議論には、あまり動かされないほうですか？", axis: "TF", weight: 1, reverse: false },
  { id: "mbti-29", text: "やるべきことを、締切ぎりぎりまで後回しにしてしまうことが多いですか？", axis: "JP", weight: 2, reverse: true },
  { id: "mbti-30", text: "倫理的なジレンマについて議論するのが好きですか？", axis: "SN", weight: 1, reverse: true },

  { id: "mbti-31", text: "一人でいるより、人と一緒にいるほうが好きですか？", axis: "EI", weight: 2, reverse: false },
  { id: "mbti-32", text: "議論がかなり理論的になると、退屈に感じたり興味を失ったりしやすいですか？", axis: "SN", weight: 1, reverse: false },
  { id: "mbti-33", text: "事実と感情がぶつかったときは、自分の心に従うことが多いですか？", axis: "TF", weight: 2, reverse: true },
  { id: "mbti-34", text: "仕事や勉強のために、一定のスケジュールを保つのは難しいと感じますか？", axis: "JP", weight: 2, reverse: true },
  { id: "mbti-35", text: "一度決めたことを、その後あまり疑わないほうですか？", axis: "JP", weight: 1, reverse: false },
  { id: "mbti-36", text: "友人からは、活発で社交的な人だと思われているほうですか？", axis: "EI", weight: 1, reverse: false },

  { id: "mbti-37", text: "文章を書くことなど、さまざまな創造的表現に惹かれますか？", axis: "SN", weight: 2, reverse: true },
  { id: "mbti-38", text: "物事を決めるときは、感情的な印象よりも客観的な事実を重視しますか？", axis: "TF", weight: 2, reverse: false },
  { id: "mbti-39", text: "1日ごとのやることリストを作るのが好きですか？", axis: "JP", weight: 2, reverse: false },
  { id: "mbti-40", text: "不安を感じることは、ほとんどないほうですか？", axis: "TF", weight: 1, reverse: false },
  { id: "mbti-41", text: "できれば電話はかけずに済ませたいと思うことが多いですか？", axis: "EI", weight: 1, reverse: true },
  { id: "mbti-42", text: "馴染みのないアイデアや新しい視点を探るのは楽しいですか？", axis: "SN", weight: 2, reverse: true },

  { id: "mbti-43", text: "初対面の相手でも、比較的すぐに理解し合えると感じることが多いですか？", axis: "EI", weight: 1, reverse: false },
  { id: "mbti-44", text: "計画が途中で乱れたときは、できるだけ早く元の流れに戻すことが大事だと思いますか？", axis: "JP", weight: 2, reverse: false },
  { id: "mbti-45", text: "かなり前に自分がした失敗でも、まだ気にしてしまうことがありますか？", axis: "TF", weight: 1, reverse: true },
  { id: "mbti-46", text: "将来の世界がどうなるかといった理論的な議論には、あまり興味がありませんか？", axis: "SN", weight: 1, reverse: false },
  { id: "mbti-47", text: "自分は感情をコントロールするより、感情に動かされやすいほうだと感じますか？", axis: "TF", weight: 1, reverse: true },
  { id: "mbti-48", text: "意思決定では、最も論理的で効率的な方法よりも、関わる人がどう感じるかを重視することが多いですか？", axis: "TF", weight: 2, reverse: true },

  { id: "mbti-49", text: "あなたの仕事の進め方は、コツコツ積み上げるというより、やる気が高まったときに一気に進めるほうに近いですか？", axis: "JP", weight: 1, reverse: true },
  { id: "mbti-50", text: "誰かに高く評価されると、その人がいつ失望するかを考えてしまうことがありますか？", axis: "TF", weight: 1, reverse: true },
  { id: "mbti-51", text: "ほとんど常に一人で進める仕事にも魅力を感じますか？", axis: "EI", weight: 2, reverse: true },
  { id: "mbti-52", text: "抽象的で哲学的な問題をじっくり考えるのは、時間の無駄だと思いますか？", axis: "SN", weight: 1, reverse: false },
  { id: "mbti-53", text: "静かな隠れ家のような場所より、人が多く賑やかな雰囲気のほうが好きですか？", axis: "EI", weight: 2, reverse: false },
  { id: "mbti-54", text: "ある決断が自分にとって正しいと感じたら、追加の証拠がなくても行動に移すことが多いですか？", axis: "TF", weight: 1, reverse: true },

  { id: "mbti-55", text: "精神的にいっぱいいっぱいだと感じることが、よくありますか？", axis: "TF", weight: 1, reverse: true },
  { id: "mbti-56", text: "手順を省かず、順番どおりに丁寧に進めるほうですか？", axis: "JP", weight: 2, reverse: false },
  { id: "mbti-57", text: "決まった手順を守る仕事よりも、創造的な解決策を考える仕事のほうが好きですか？", axis: "SN", weight: 2, reverse: true },
  { id: "mbti-58", text: "意思決定では、論理的な推論よりも感情的な直感に頼ることが多いですか？", axis: "TF", weight: 2, reverse: true },
  { id: "mbti-59", text: "締切を守るのは苦手なほうですか？", axis: "JP", weight: 2, reverse: true },
  { id: "mbti-60", text: "自分に関係することは、うまくいくだろうと自信を持ちやすいですか？", axis: "TF", weight: 1, reverse: false },

  { id: "mbti-61", text: "会話の中では、自分から話題を広げることが多いですか？", axis: "EI", weight: 2, reverse: false },
  { id: "mbti-62", text: "新しい人間関係を広げるよりも、限られた人と深く関わるほうが心地よいですか？", axis: "EI", weight: 2, reverse: true },
  { id: "mbti-63", text: "目の前の現実よりも、まだ形になっていない可能性を考えることが多いですか？", axis: "SN", weight: 2, reverse: true },
  { id: "mbti-64", text: "新しい発想よりも、実績のあるやり方のほうが安心できますか？", axis: "SN", weight: 2, reverse: false },
  { id: "mbti-65", text: "相手の気持ちに配慮して、自分の意見をやわらかく伝えることが多いですか？", axis: "TF", weight: 2, reverse: true },
  { id: "mbti-66", text: "相手がどう感じるかよりも、結論として正しいかどうかを優先することが多いですか？", axis: "TF", weight: 2, reverse: false },
  { id: "mbti-67", text: "予定が決まっているほうが安心して動けますか？", axis: "JP", weight: 2, reverse: false },
  { id: "mbti-68", text: "その場で選択肢を残しながら進めるほうが、自分に合っていると感じますか？", axis: "JP", weight: 2, reverse: true },
  { id: "mbti-69", text: "多くの人と関わる場にいると、自然と気分が上がるほうですか？", axis: "EI", weight: 2, reverse: false },
  { id: "mbti-70", text: "事実として確認できるものを土台にして考えるほうですか？", axis: "SN", weight: 2, reverse: false },
  { id: "mbti-71", text: "判断のときは、周囲との調和よりも筋が通っているかを見ますか？", axis: "TF", weight: 2, reverse: false },
  { id: "mbti-72", text: "締切が先でも、早めに取りかかっておきたいタイプですか？", axis: "JP", weight: 2, reverse: false },
];

export const businessQuestions: BusinessQuestion[] = [
  { id: "business-1", question: "新しい業務を任された直後、あなたの動き方として近いのはどちらですか？", optionA: "まず全体の流れや進め方を整理してから動く", optionB: "まず手を動かしながら状況を把握していく", axis: "MP", weight: 2, reverse: false },
  { id: "business-2", question: "会議に参加する前の準備として近いのはどちらですか？", optionA: "議題や論点を事前に確認して整理しておく", optionB: "会議が始まってから流れをつかむ", axis: "MP", weight: 2, reverse: false },
  { id: "business-3", question: "初めてのプロジェクト説明を受けた直後、最初にすることとして近いのはどちらですか？", optionA: "全体像や役割を整理しながら理解する", optionB: "できるところから着手して、動きながら理解する", axis: "MP", weight: 2, reverse: false },
  { id: "business-4", question: "よく知らない領域の仕事を任されたとき、近い動き方はどちらですか？", optionA: "まず背景や前提、似た事例を一通り押さえたい", optionB: "まず簡単に手をつけて、必要な情報を進めながら拾いたい", axis: "MP", weight: 1, reverse: false },
  { id: "business-5", question: "依頼を受けたときの最初の一歩として近いのはどちらですか？", optionA: "背景や目的を確認してから着手したい", optionB: "まず進めながら背景を補完していきたい", axis: "MP", weight: 2, reverse: false },
  { id: "business-6", question: "トラブルが起きたときの対応として近いのはどちらですか？", optionA: "状況を整理してから対応方針を決める", optionB: "まず動いて状況を改善しながら考える", axis: "MP", weight: 2, reverse: false },
  { id: "business-7", question: "新しいツールを使うときの進め方として近いのはどちらですか？", optionA: "使い方や全体像を理解してから触る", optionB: "触りながら使い方を覚えていく", axis: "MP", weight: 1, reverse: false },
  { id: "business-8", question: "チームでの役割として自然なのはどちらですか？", optionA: "全体の進行や方向性を整理する役割", optionB: "実務を進めて成果を出す役割", axis: "MP", weight: 2, reverse: false },
  { id: "business-9", question: "プロジェクト成功のために重要だと思うのはどちらですか？", optionA: "しっかりした計画や設計", optionB: "スピード感のある実行", axis: "MP", weight: 2, reverse: false },
  { id: "business-10", question: "チームに入ったとき、無意識に取りやすい立ち位置はどちらですか？", optionA: "まず全体を見て整理役に回る", optionB: "まず自分の担当を進めて前に出す", axis: "MP", weight: 2, reverse: false },
  { id: "business-11", question: "仕事を進めるうえで安心できるのはどちらですか？", optionA: "全体像と優先順位が見えていること", optionB: "まず着手して手応えをつかめていること", axis: "MP", weight: 2, reverse: false },
  { id: "business-12", question: "新しいアイデアを思いついたとき、最初にやりやすいのはどちらですか？", optionA: "どう進めるかを整理して形にする", optionB: "まず試してみて反応を確かめる", axis: "MP", weight: 1, reverse: false },

  { id: "business-13", question: "仕事の振り返りで重視するものとして近いのはどちらですか？", optionA: "自分がどれだけ成長したか", optionB: "周囲にどれだけ価値を返せたか", axis: "QR", weight: 2, reverse: false },
  { id: "business-14", question: "新しい役割の話をもらったとき、まず考えるのはどちらですか？", optionA: "その役割で自分がどれだけ成長できるか", optionB: "その役割で誰にどんな価値を返せるか", axis: "QR", weight: 2, reverse: false },
  { id: "business-15", question: "努力が報われたと感じるのはどちらですか？", optionA: "前より自分ができるようになっているとき", optionB: "周囲から感謝や信頼を得られたとき", axis: "QR", weight: 2, reverse: false },
  { id: "business-16", question: "仕事を続ける理由として近いのはどちらですか？", optionA: "自分のスキルや可能性を広げたいから", optionB: "誰かや組織の役に立ちたいから", axis: "QR", weight: 2, reverse: false },
  { id: "business-17", question: "キャリアを考えるとき、より気になるのはどちらですか？", optionA: "自分がどこまで成長できるか", optionB: "周囲にどれだけ価値を返せるか", axis: "QR", weight: 1, reverse: false },
  { id: "business-18", question: "上司との面談で話したいテーマとして近いのはどちらですか？", optionA: "自分の将来や、ありたい姿について", optionB: "チームや周囲にどう貢献できるかについて", axis: "QR", weight: 1, reverse: false },
  { id: "business-19", question: "やる気が高まりやすいきっかけとして近いのはどちらですか？", optionA: "自分が目指したい姿に近づける実感", optionB: "誰かの役に立てる実感", axis: "QR", weight: 2, reverse: false },
  { id: "business-20", question: "新しい挑戦に向かう理由として近いのはどちらですか？", optionA: "自分の可能性を広げたいから", optionB: "周囲や組織により良い影響を出したいから", axis: "QR", weight: 1, reverse: false },
  { id: "business-21", question: "仕事で一番嬉しい瞬間として近いのはどちらですか？", optionA: "自分の成長をはっきり感じたとき", optionB: "誰かに価値を届けられたと実感したとき", axis: "QR", weight: 2, reverse: false },
  { id: "business-22", question: "評価されたいポイントとして近いのはどちらですか？", optionA: "自分が前より成長していること", optionB: "周囲に良い影響を与えていること", axis: "QR", weight: 2, reverse: false },
  { id: "business-23", question: "仕事に意味を感じるのはどちらですか？", optionA: "自分の可能性が広がっていくとき", optionB: "相手や組織に良い変化を生めたとき", axis: "QR", weight: 2, reverse: false },
  { id: "business-24", question: "挑戦するテーマを選ぶなら、より近いのはどちらですか？", optionA: "自分を伸ばせるテーマ", optionB: "誰かの役に立てるテーマ", axis: "QR", weight: 1, reverse: false },

  { id: "business-25", question: "仕事を選ぶとき、より重視するのはどちらですか？", optionA: "自分が納得して熱量を持てる内容か", optionB: "条件や働く環境が安定しているか", axis: "VT", weight: 2, reverse: false },
  { id: "business-26", question: "オファーや役割相談が来たとき、まず重視するのはどちらですか？", optionA: "仕事内容にワクワクするか", optionB: "条件面が現実的に合っているか", axis: "VT", weight: 2, reverse: false },
  { id: "business-27", question: "毎日の仕事スタイルとして近いのはどちらですか？", optionA: "多少効率が落ちても、自分が納得できる進め方を選びがち", optionB: "まずは効率の良い進め方を選ぶことが多い", axis: "VT", weight: 1, reverse: false },
  { id: "business-28", question: "資料やドキュメント作成の最初の一手として近いのはどちらですか？", optionA: "数字や事実、根拠を整理してから組み立てる", optionB: "伝えたいストーリーやメッセージから組み立てる", axis: "VT", weight: 1, reverse: false },
  { id: "business-29", question: "迷ったときに背中を押すものとして近いのはどちらですか？", optionA: "自分にとって意味があると思えること", optionB: "無理なく続けられる条件がそろっていること", axis: "VT", weight: 2, reverse: false },
  { id: "business-30", question: "仕事の満足度を左右するものとして近いのはどちらですか？", optionA: "仕事そのものにやりがいや意味を感じられること", optionB: "働く環境や制度、待遇が整っていること", axis: "VT", weight: 2, reverse: false },
  { id: "business-31", question: "長く働きたいと思えるのはどちらですか？", optionA: "夢中になれる仕事がある職場", optionB: "安定した条件で安心して続けられる職場", axis: "VT", weight: 2, reverse: false },
  { id: "business-32", question: "会社に求めるものとして近いのはどちらですか？", optionA: "挑戦できるテーマや機会", optionB: "待遇や制度の充実", axis: "VT", weight: 1, reverse: false },
  { id: "business-33", question: "多少条件が厳しくても頑張れるのはどちらですか？", optionA: "面白くて意味を感じられる仕事", optionB: "条件が明確で見通しが立つ仕事", axis: "VT", weight: 2, reverse: false },
  { id: "business-34", question: "転職や異動を考えるとき、最後に決め手になりやすいのはどちらですか？", optionA: "やってみたいと思える内容かどうか", optionB: "条件や環境に無理がないかどうか", axis: "VT", weight: 2, reverse: false },
  { id: "business-35", question: "日々の納得感につながるのはどちらですか？", optionA: "意味のある仕事をしている感覚", optionB: "現実的に無理なく働ける感覚", axis: "VT", weight: 2, reverse: false },
  { id: "business-36", question: "新しい挑戦を引き受けるか迷うとき、より近いのはどちらですか？", optionA: "面白さや意義があるなら前向きになる", optionB: "条件が合っているなら前向きになる", axis: "VT", weight: 1, reverse: false },

  { id: "business-37", question: "突然の方針変更が起きたとき、先に立ち上がる感覚として近いのはどちらですか？", optionA: "まず可能性や面白さに目が向く", optionB: "まずリスクや現実性が気になる", axis: "CS", weight: 2, reverse: false },
  { id: "business-38", question: "大きな決断をするとき、より近いのはどちらですか？", optionA: "多少不確実でも理想に近いほうを選びたい", optionB: "まず失敗しにくく安定したほうを選びたい", axis: "CS", weight: 2, reverse: false },
  { id: "business-39", question: "新しい企画が出たときの反応として近いのはどちらですか？", optionA: "まずやってみたいと感じる", optionB: "まず現実的に成立するかを確かめたい", axis: "CS", weight: 2, reverse: false },
  { id: "business-40", question: "行動を決めるときに重視するのはどちらですか？", optionA: "理想に近づけるかどうか", optionB: "安全に進められるかどうか", axis: "CS", weight: 2, reverse: false },
  { id: "business-41", question: "未知の仕事に対して近いのはどちらですか？", optionA: "まず挑戦してみたい", optionB: "失敗しにくい進め方を確認したい", axis: "CS", weight: 2, reverse: false },
  { id: "business-42", question: "新しい方法を試すとき、より近いのはどちらですか？", optionA: "可能性があるならまずやってみたい", optionB: "安全性や再現性を確認してからにしたい", axis: "CS", weight: 1, reverse: false },
  { id: "business-43", question: "チャンスが来たときの反応として近いのはどちらですか？", optionA: "まず飛び込んでみたい", optionB: "慎重に見極めてから動きたい", axis: "CS", weight: 2, reverse: false },
  { id: "business-44", question: "新しい環境に入るとき、より近いのはどちらですか？", optionA: "ワクワクが先に立つ", optionB: "不安や慎重さが先に立つ", axis: "CS", weight: 1, reverse: false },
  { id: "business-45", question: "最後に意思決定を後押しするものとして近いのはどちらですか？", optionA: "理想に近づける実感", optionB: "リスクを抑えられる安心感", axis: "CS", weight: 2, reverse: false },
  { id: "business-46", question: "経験のない仕事の話が来たとき、より近いのはどちらですか？", optionA: "まず成長や可能性を感じる", optionB: "まず失敗リスクを見積もりたくなる", axis: "CS", weight: 2, reverse: false },
  { id: "business-47", question: "判断に迷う局面で、自分を動かしやすいのはどちらですか？", optionA: "多少不安でも前に進むほう", optionB: "まず安全な形を確保するほう", axis: "CS", weight: 2, reverse: false },
  { id: "business-48", question: "新しい選択肢に出会ったとき、より自然なのはどちらですか？", optionA: "まず可能性を広げる方向で考える", optionB: "まず確実に守れる線を考える", axis: "CS", weight: 1, reverse: false },
];

export const mbtiReverseQuestions: MbtiLikertQuestion[] = [
  { id: "mbti-reverse-1", axis: "EI", direction: "E", question: "多くの人と関わる場にいると、自然と気分が上がることが多い" },
  { id: "mbti-reverse-2", axis: "EI", direction: "I", question: "一人の時間がないと疲れやすく、落ち着かない" },
  { id: "mbti-reverse-3", axis: "SN", direction: "S", question: "発想の面白さよりも、現実的に使えるかどうかを重視する" },
  { id: "mbti-reverse-4", axis: "SN", direction: "N", question: "今ある事実よりも、まだ見えていない可能性を考えることが多い" },
  { id: "mbti-reverse-5", axis: "TF", direction: "T", question: "相手の気持ちよりも、筋が通っているかどうかで判断しやすい" },
  { id: "mbti-reverse-6", axis: "TF", direction: "F", question: "正しさよりも、相手がどう感じるかを優先することが多い" },
  { id: "mbti-reverse-7", axis: "JP", direction: "J", question: "予定が決まっているほうが安心して動ける" },
  { id: "mbti-reverse-8", axis: "JP", direction: "P", question: "その場で柔軟に変えながら進めるほうが自分に合っている" },
];

export const mbtiConsistencyQuestions: MbtiLikertQuestion[] = [
  { id: "mbti-consistency-1", axis: "EI", direction: "E", question: "初対面の相手とも、自分から会話を広げるほうだ" },
  { id: "mbti-consistency-2", axis: "EI", direction: "I", question: "人と長く一緒にいるより、一人で過ごすほうが回復しやすい" },
  { id: "mbti-consistency-3", axis: "SN", direction: "S", question: "抽象的な理論より、具体的な事実や実績のほうが信頼しやすい" },
  { id: "mbti-consistency-4", axis: "SN", direction: "N", question: "現実よりも可能性や発想を考えている時間が好きだ" },
  { id: "mbti-consistency-5", axis: "TF", direction: "T", question: "判断するときは、まず論理的に説明できるかを気にする" },
  { id: "mbti-consistency-6", axis: "TF", direction: "F", question: "結論を出すときは、人間関係への影響を強く意識する" },
  { id: "mbti-consistency-7", axis: "JP", direction: "J", question: "物事は前もって計画して、順序立てて進めたい" },
  { id: "mbti-consistency-8", axis: "JP", direction: "P", question: "あらかじめ決め込みすぎず、状況に合わせて動きたい" },
];

export const businessReverseQuestions: BusinessLikertQuestion[] = [
  { id: "business-reverse-1", axis: "MP", direction: "M", question: "仕事ではまず全体の流れや構造を整理してから動くことが多い" },
  { id: "business-reverse-2", axis: "MP", direction: "P", question: "計画を固めるより、まず手を動かして状況をつかむほうが得意だ" },
  { id: "business-reverse-3", axis: "QR", direction: "Q", question: "仕事は、自分がどれだけ成長できるかを重視したい" },
  { id: "business-reverse-4", axis: "QR", direction: "R", question: "人の役に立っていると感じると、やりがいが高まる" },
  { id: "business-reverse-5", axis: "VT", direction: "V", question: "条件よりも、仕事そのものに意味や面白さを感じられることが大切だ" },
  { id: "business-reverse-6", axis: "VT", direction: "T", question: "やりがいがあっても、条件や環境が厳しい仕事は続けにくい" },
  { id: "business-reverse-7", axis: "CS", direction: "C", question: "多少リスクがあっても、新しいことには挑戦したいと思う" },
  { id: "business-reverse-8", axis: "CS", direction: "S", question: "理想よりも、失敗しにくく安全に進められる選択を取りやすい" },
];

export const businessConsistencyQuestions: BusinessLikertQuestion[] = [
  { id: "business-consistency-1", axis: "MP", direction: "M", question: "チームでは、全体の進行や方向性を整理する役割になりやすい" },
  { id: "business-consistency-2", axis: "MP", direction: "P", question: "全体設計よりも、まず現場で実務を進めて成果を出すほうが自然だ" },
  { id: "business-consistency-3", axis: "QR", direction: "Q", question: "誰かのためというより、自分が前に進めている実感があると燃える" },
  { id: "business-consistency-4", axis: "QR", direction: "R", question: "自分の成長以上に、周囲へ価値を返せたときの満足感が大きい" },
  { id: "business-consistency-5", axis: "VT", direction: "V", question: "多少条件が悪くても、意味のある仕事なら頑張れる" },
  { id: "business-consistency-6", axis: "VT", direction: "T", question: "仕事を続けるうえでは、納得できる条件や環境が欠かせない" },
  { id: "business-consistency-7", axis: "CS", direction: "C", question: "新しい挑戦や未知の環境に対して、まず前向きさが先に立つ" },
  { id: "business-consistency-8", axis: "CS", direction: "S", question: "大きな判断では、理想よりも現実的な安全性を重視する" },
];